"""Tests for scripts/prune-canonical-renders.sh (pst-dm9).

Builds throwaway git repos that mirror the CI commit-back setup: a
base commit (main) with canonical renders, a PR branch whose renders
carry local byte-noise, and a staged CI regeneration. The script must
drop staged changes that byte-match the base commit and keep the rest.

Not wired into the CI pytest step (that step's scope is
scripts/invariants/ and widening it was outside the pst-dm9 workflow
exception); run locally with `python3 -m pytest scripts/`.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "prune-canonical-renders.sh"


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _write(repo: Path, rel: str, content: str) -> None:
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    """A repo shaped like the CI /tmp clone: base commit with canonical
    renders, PR branch with locally rendered (byte-noisy) variants."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.name", "test")
    _git(repo, "config", "user.email", "test@example.com")

    _write(repo, "renders/alpha/iso.png", "canonical-alpha")
    _write(repo, "renders/beta/iso.png", "canonical-beta")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "base: canonical renders")

    _git(repo, "checkout", "-q", "-b", "pr")
    _write(repo, "renders/alpha/iso.png", "local-noise-alpha")
    _write(repo, "renders/beta/iso.png", "local-beta-changed")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "pr: locally rendered thumbnails")
    return repo


def _base_sha(repo: Path) -> str:
    return _git(repo, "rev-parse", "main")


def _run_script(repo: Path) -> str:
    result = subprocess.run(
        ["bash", str(SCRIPT), _base_sha(repo)],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def _staged(repo: Path) -> list[str]:
    out = _git(repo, "diff", "--cached", "--name-only")
    return out.splitlines() if out else []


def test_prunes_base_matches_keeps_real_changes(repo: Path) -> None:
    # CI regeneration: alpha reproduces the canonical bytes (model
    # unchanged — the PR's diff was renderer noise); beta genuinely
    # changed and renders to new bytes.
    _write(repo, "renders/alpha/iso.png", "canonical-alpha")
    _write(repo, "renders/beta/iso.png", "ci-canonical-beta-v2")
    _git(repo, "add", "renders/")

    out = _run_script(repo)

    assert _staged(repo) == ["renders/beta/iso.png"]
    # alpha restored to the PR branch's own version, not left half-staged
    assert (repo / "renders/alpha/iso.png").read_text() == "local-noise-alpha"
    assert "pruned=1 kept=1" in out


def test_all_matches_leaves_tree_identical_to_head(repo: Path) -> None:
    # Every regenerated PNG matches base: the follow-up tree-hash check
    # in the workflow must see "nothing to commit".
    _write(repo, "renders/alpha/iso.png", "canonical-alpha")
    _write(repo, "renders/beta/iso.png", "canonical-beta")
    _git(repo, "add", "renders/")

    _run_script(repo)

    assert _staged(repo) == []
    new_tree = _git(repo, "write-tree")
    head_tree = _git(repo, "rev-parse", "HEAD^{tree}")
    assert new_tree == head_tree


def test_new_file_absent_from_base_is_kept(repo: Path) -> None:
    # A model added by the PR has no base render — always keep it.
    _write(repo, "renders/gamma/iso.png", "ci-canonical-gamma")
    _git(repo, "add", "renders/")

    out = _run_script(repo)

    assert "renders/gamma/iso.png" in _staged(repo)
    assert "pruned=0" in out


def test_readd_of_pr_deleted_path_matching_base_is_dropped(repo: Path) -> None:
    # PR deleted a render; CI regenerated bytes identical to base.
    # Keep the PR's deletion rather than re-adding the canonical copy.
    _git(repo, "rm", "-q", "renders/beta/iso.png")
    _git(repo, "commit", "-q", "-m", "pr: drop beta render")

    _write(repo, "renders/beta/iso.png", "canonical-beta")
    _git(repo, "add", "renders/")

    _run_script(repo)

    assert _staged(repo) == []
    assert not (repo / "renders/beta/iso.png").exists()


def test_staged_deletion_is_kept(repo: Path) -> None:
    # A staged deletion never byte-matches a base blob; leave it alone.
    _git(repo, "rm", "-q", "renders/alpha/iso.png")

    _run_script(repo)

    assert _staged(repo) == ["renders/alpha/iso.png"]
